name: reddwarf_dict
description: A convenient translation and dictionary app written in dart / Flutter.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.3.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^0.19.1
  bot_toast: ^4.0.1
  device_info_plus: ^3.1.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  hotkey_manager: ^0.1.4
  libwinmedia: ^0.0.5
  package_info_plus: ^1.0.4
  fluttertoast: 8.0.3
  get: ^4.3.8
  photo_view: ^0.12.0
  pro_account:
    git:
      ref: main
      url: https://github.com/jiangxiaoqiang/pro_account_noop.git
  screen_retriever: ^0.0.2
  screen_text_extractor: ^0.0.1
  sticky_headers: ^0.1.8
  tray_manager: ^0.1.0
  uni_links: ^0.5.1
  flutter_launcher_icons: ^0.9.0
  uni_links_macos:
    git:
      path: packages/uni_links_macos
      ref: master
      url: https://github.com/biyidev/dart_pkgs.git
  uni_ocr:
    git:
      path: packages/uni_ocr
      ref: master
      url: https://github.com/jiangxiaoqiang/uni_ocr.git
  uni_ocr_client:
    git:
      path: packages/uni_ocr_client
      ref: master
      url: https://github.com/jiangxiaoqiang/uni_ocr.git
  uni_translate:
    git:
      path: packages/uni_translate
      ref: master
      url: https://github.com/jiangxiaoqiang/uni_translate.git
  uni_translate_client:
    git:
      path: packages/uni_translate_client
      ref: master
      url: https://github.com/jiangxiaoqiang/uni_translate.git
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  window_manager: ^0.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  wheel:
    git:
      url: https://github.com/jiangxiaoqiang/wheel.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  archive: ^3.1.5
  msix: ^2.1.3

flutter_icons:
  image_path: "assets/images/translation_engine_icons/reddwarf1024.png"
  android: true
  ios: true

dependency_overrides:
  uni_translate_client:
    git:
      path: packages/uni_translate_client
      ref: master
      url: https://github.com/jiangxiaoqiang/uni_translate.git

flutter:
  uses-material-design: true

  assets:
    - assets/environments/
    - assets/images/
    - assets/images/flag_icons/
    - assets/images/ocr_engine_icons/
    - assets/images/translation_engine_icons/
    - assets/translations/
    - assets/cfg/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
