name: reddwarfdict
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  fluttertoast: 8.0.3
  json_annotation: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^5.0.0

  flutter_lints: ^1.0.0
  wheel:
    git:
      url: https://github.com/jiangxiaoqiang/wheel.git
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
